### PR TITLE
Set price limit for pastry and fix error messages

### LINKED ISSUE #246: [PE-D][Tester A] Allowing Free Pastry
Not sure whether this is a design choice or a bug. Currently your application is accepting pastry that is sold with price 0 (free). 

To reproduce: enter `add pastry Croissant -pr 0`.

￼

If it is designed in this manner (for special event like buy one get one free), probably you can add this design choice into your user guide:)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: RickyHFR/ped#3

### LINKED ISSUE #250: [PE-D][Tester E] Result display bug for overly precise prices
I am trying to sell "smol bread" here, and decided to price it at 0.001 for some reason. I guess the addition fails because there are 3 digits after the floating point, but the error message says prices should only contain digits, but that price follows this rule.

A message to tell the user about the precision of prices would help

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ryanlow64/ped#4

### LINKED ISSUE #254: [PE-D][Tester A] Not Detailed Instruction for Pastry Price When Adding New Pastry
This issue is regarding the error message I encountered after entering an invalid price for new pastry. To reproduce, enter `add pastry Strawberry Cake -pr 5.500`.

￼
Although you have already included the reminder that a price can only be in two decimal places (which is great!), it would be better to state it explicity in the message displayed in PowerBake! (I know it seems to be common sense that a price should be in 2 d.p. xD)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RickyHFR/ped#5

### LINKED ISSUE #295: [PE-D][Tester B] Prices do not allow for valid prices
### Description:
Overzealous input validation of price causes valid and commonly used price formats to be considered invalid.

### Steps to Reproduce:
`add pastry Croissant -pr .99`

### Expected Behavior:
Add pastry with a price of $0.99.

### Observed Behavior:
`Prices should only contain digits, such as 3, 6.5 or 123.57`

### Screenshot(s):

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Zhannyhong/ped#9

### LINKED ISSUE #299: [PE-D][Tester B] Inaccurate error message for prices
### Description:
Although only digits were provided, error message suggests that non-digits were provided.

### Steps to Reproduce:
`add pastry Croissant -pr 3.1415`

### Expected Behavior:
Message should indicate that price should only have 2 decimal places.

### Observed Behavior:
`Prices should only contain digits, such as 3, 6.5 or 123.57`

### Screenshot(s):

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Zhannyhong/ped#10

### LINKED ISSUE #302: [PE-D][Tester B] Large prices not validated
### Description:
Large pastry prices are truncated prematurely to 17 digits. This causes the price recorded to be reflected differently from the input, causing inconsistencies. Furthermore, the lack of validation may cause downstream problems when calculating order prices due to possible overflow issues.

### Steps to Reproduce:
`add pastry Croissant -pr 123456789123456789123456789123456789`

### Expected Behavior:
Such extreme values should not be allowed as it does not make sense for a pastry to be this expensive. Unless it really is that delicious.

### Observed Behavior:
`New pastry added: Croissant; Price: 123456789123456780000000000000000000.00`

### Screenshot(s):

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Zhannyhong/ped#11

### LINKED ISSUE #308: [PE-D][Tester B] Large prices displayed differently on pastry and order page
### Description:
If a large price was provided previously is longer than 17 digits, the `truncated price * quantity` does not match the total price order due to possible rounding error.

### Steps to Reproduce:
`add pastry Croissant -pr 123456789123456789123456789123456789`, then `add order 1 -pn Croissant -q 3`

### Expected Behavior:
Total price should be $37037036737037034

### Observed Behavior:
Total price is $37037036737037035

### Screenshot(s):

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Zhannyhong/ped#12

### PR DESCRIPTION
**Pull request by mihirniyogi**
Fixes #308, Fixes #302, Fixes #299, Fixes #295, Fixes #254, Fixes #250, Fixes #246

### CODE REVIEW

File: src/main/java/powerbake/address/model/pastry/Price.java [hunk 1]
```diff
@@ -9,7 +9,7 @@
  */
 public class Price {
     public static final String MESSAGE_CONSTRAINTS =
-        "Prices should only contain digits, such as 3, 6.5 or 123.57";
+        "Prices should only contain digits and up to 2 decimal points, such as 3, 12.5 or 0.99";
```
Comment (Mil-leon) [inline src/main/java/powerbake/address/model/pastry/Price.java:12]: Nice understandable specification :)

File: src/main/java/powerbake/address/commons/util/StringUtil.java [hunk 2]
```diff
@@ -79,4 +79,18 @@ public static boolean isValidIntegerQuantity(String s) {
...
+
+    /**
+     * Returns true if {@code s} represents a double between 1 - 999
+     * @throws NullPointerException if {@code s} is null.
+     */
+    public static boolean isValidPrice(String s) {
+        requireNonNull(s);
+        try {
+            double value = Double.parseDouble(s);
+            return value > 0.0 && value <= 999.99 && !s.startsWith("+");
```
Comment (mogmyij) [inline src/main/java/powerbake/address/commons/util/StringUtil.java:91]: Nice this will make PowerBake more robust!

**Review by mogmyij — COMMENTED** [review]
LGTM!

File: src/test/java/powerbake/address/commons/util/StringUtilTest.java [hunk 3]
```diff
@@ -63,6 +65,33 @@ public void isValidIntegerQuantity() {
         assertTrue(StringUtil.isValidIntegerQuantity("999"));
     }
 
+    //---------------- Tests for isValidPrice --------------------------------------
+
+    @Test
+    public void isValidPrice() {
```
Comment (Mil-leon) [inline src/test/java/powerbake/address/commons/util/StringUtilTest.java:71]: Good test cases for testing

**Review by Mil-leon — COMMENTED** [review]
LGTM
