### PR TITLE
Fix view order index out of range error message

### LINKED ISSUE #169: Viewing negative numbers does return appropriate error message
Image

Error message could instead be "Invalid index for order"

### PR DESCRIPTION
**Pull request by mogmyij**
Fixes #169

### CODE REVIEW

File: src/main/java/powerbake/address/logic/commands/ViewCommand.java [hunk 1]
```diff
@@ -56,24 +58,25 @@ public CommandResult execute(Model model) throws CommandException {
...
-
         if (type.equals("client")) {
             model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
         } else if (type.equals("pastry")) {
             model.updateFilteredPastryList(PREDICATE_SHOW_ALL_PASTRIES);
         } else if (type.equals("order")) {
-            if (index != null) {
-                // do nothing
-            } else {
+            if (index == null) {
```
Comment (Mil-leon) [inline src/main/java/powerbake/address/logic/commands/ViewCommand.java:66]: Nice fix for the empty if condition 👍

**Review by Mil-leon — COMMENTED** [review]
LGTM
