### PR TITLE
Fix grammar errors

### LINKED ISSUE #272: [PE-D][Tester C] Incorrect plural form used in find command result for singular match
When using the find pastry command and exactly one result is found, the message displays: 1 pastries listed!
This is grammatically incorrect. For a single result, the singular form "pastry" should be used instead of "pastries".
Assuming there is 1 pastry called chocolate muffin:
Command run: find pastry Chocolate
Expected output: 1 pastry listed!
Actual output: 1 pastries listed!

Suggested Fix:
Implement a conditional check in the message generation logic to use:
"1 pastry listed!" for exactly 1 match.
"X pastries listed!" for all other counts.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: coffeemocha/ped#6

### LINKED ISSUE #303: [PE-D][Tester E] Find command grammatical error
When a find command returns more than 1 result, the relevant item is not in plural form.

To reproduce, have multiple items to match the keyword, and find using that keyword.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: ryanlow64/ped#14

### PR DESCRIPTION
**Pull request by Mil-leon**
Fixes #272 and Fixes #303

### CODE REVIEW

File: src/main/java/powerbake/address/logic/Messages.java [hunk 1]
```diff
@@ -24,9 +24,9 @@ public class Messages {
     public static final String MESSAGE_INVALID_INDEX = "The index provided is out of range.";
     public static final String MESSAGE_INVALID_PASTRY_DISPLAYED = "The pastry name provided is invalid";
     public static final String MESSAGE_REPEATED_PASTRY_IN_ORDER = "The pastry name is repeated in order command";
-    public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d client listed!";
-    public static final String MESSAGE_PASTRIES_LISTED_OVERVIEW = "%1$d pastries listed!";
-    public static final String MESSAGE_ORDERS_LISTED_OVERVIEW = "%1$d orders listed!";
+    public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d client(s) listed!";
+    public static final String MESSAGE_PASTRIES_LISTED_OVERVIEW = "%1$d pastry(ies) listed!";
+    public static final String MESSAGE_ORDERS_LISTED_OVERVIEW = "%1$d order(s) listed!";
```
Comment (Emmanuel2001) [inline src/main/java/powerbake/address/logic/Messages.java:29]: Good job!

**Review by Emmanuel2001 — COMMENTED** [review]
LGTM!

File: src/main/java/powerbake/address/logic/Messages.java [hunk 2]
```diff
@@ -24,9 +24,9 @@ public class Messages {
     public static final String MESSAGE_INVALID_INDEX = "The index provided is out of range.";
     public static final String MESSAGE_INVALID_PASTRY_DISPLAYED = "The pastry name provided is invalid";
     public static final String MESSAGE_REPEATED_PASTRY_IN_ORDER = "The pastry name is repeated in order command";
-    public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d client listed!";
-    public static final String MESSAGE_PASTRIES_LISTED_OVERVIEW = "%1$d pastries listed!";
-    public static final String MESSAGE_ORDERS_LISTED_OVERVIEW = "%1$d orders listed!";
+    public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d client(s) listed!";
```
Comment (mogmyij) [inline src/main/java/powerbake/address/logic/Messages.java:27]: Good change this will make PowerBake less confusing for users!

**Review by mogmyij — COMMENTED** [review]
LGTM!
