### PR TITLE
Fix error messages

### LINKED ISSUE #244: [PE-D][Tester A] Incoherent Product Name in Certain Situations
This issue is about how in some situations the messages shown in your product display "AddressBook" instead of PowerBake (sorry again for putting it under DocumentationBug).

1. After entering `clear` command.

￼
2. After entering any invalid add client command (such as `add client Amy`).
￼

3. After entering any invalid add command (such as `add Amy`).
￼

There could potentially be more of such instances that I have not found out.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: RickyHFR/ped#2

### LINKED ISSUE #265: [PE-D][Tester B] Commands are not case-insensitive
### Description:
Valid commands are detected as invalid if they are capitalised.

### Steps to Reproduce:
Typing `ADD client Luke -p 88776655 -a 5 Punggol Street -e luke@gmail.com` or `add CLIENT Luke -p 88776655 -a 5 Punggol Street -e luke@gmail.com` into the command input.

### Expected Behavior:
Expect valid commands to be accepted regardless of capitalisation.

### Observed Behavior:
Unknown command or invalid command format.

### Screenshot(s):

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Zhannyhong/ped#1

### LINKED ISSUE #277: [PE-D][Tester D] Wording of parameters
According to the UG, `add pastry` is a command. 

A description of `add pastry` appears whenever the wrong input is put in. 

This seems to suggest that `pastry` is a parameter. This could mean:
1. `add pastry` is a command that accepts `NAME -pr PRICE` as parameter.
- command would be `add pastry Bread -pr 5.5`
- user output is wrong
2. `add`  is a command that accepts `pastry NAME -pr PRICE` as parameter.
- command would be `add pastry Bread -pr 5.5`
- user output is wrong
3. `add pastry`  is a command that accepts `pastry NAME -pr PRICE` as parameter.
- command would be `add pastry pastry Bread -pr 5.5`
- unlikely, but still a confusing possibility to users.

Could we rephrase things?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: loyaltypollution/ped#10

### LINKED ISSUE #325: Change add pastry command message to PASTRY_NAME

### PR DESCRIPTION
**Pull request by mogmyij**
Fixes #277 
Fixes #244
Fixes #325 
Fixes #265

### CODE REVIEW

File: src/main/java/powerbake/address/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -43,7 +43,7 @@ public Command parseCommand(String userInput) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, HelpCommand.MESSAGE_USAGE));
         }
 
-        final String commandWord = matcher.group("commandWord");
+        final String commandWord = matcher.group("commandWord").toLowerCase();
```
Comment (cyhni) [inline src/main/java/powerbake/address/logic/parser/AddressBookParser.java:46]: Nice catch! Huge improvement to usability!

**Review by cyhni — COMMENTED** [review]
LGTM
