### PR TITLE
Fix error message with formatting artifacts

### LINKED ISSUE #260: [PE-D][Tester C] Error message shows raw placeholder (%1$s) instead of formatted text
When entering an invalid client index in the add order command, the error message includes an unformatted placeholder %1$s at the end. This seems to be a formatting string that wasn't replaced properly in the final output.
Command run: add order 999 -pn Croissant -q 1 (Assuming no client exists at 999)
Expected output: The client index provided is invalid.
Actual output: The client index provided is invalid. %1$s
Sample screenshot:

Suggested fix: Minor cosmetic issue but might confuse users who think its part of the syntax. Perhaps ensuring string is formatted with correct arguments

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: coffeemocha/ped#2

### PR DESCRIPTION
**Pull request by mogmyij**
Fixes #260

### CODE REVIEW

File: src/main/java/powerbake/address/logic/commands/AddOrderCommand.java [hunk 1]
```diff
@@ -85,7 +85,10 @@ private Person getValidClient(Model model) throws CommandException {
         List<Person> lastShownList = model.getFilteredPersonList();
 
         if (clientIndex.getZeroBased() >= lastShownList.size()) {
-            throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+            throw new CommandException(String.format(
```
Comment (cyhni) [inline src/main/java/powerbake/address/logic/commands/AddOrderCommand.java:88]: Thanks for updating error messages!

**Review by cyhni — COMMENTED** [review]
LGTM
