### PR TITLE
Fix pastry case sensitivity

### LINKED ISSUE #140: Fix case sensitivity for pastry duplication check
## Problem

Features affected: Add Pastry, Add Order

When adding a pastry, app will only throw a`DuplicatePastryException` if there is another pastry with exact match (but it should also include case insensitive matches)

For `add pastry cheesecake -pr 4.00` for example, it will allow even if there is already exists 'Cheesecake' (but it should not).

Image

### PR DESCRIPTION
**Pull request by Mil-leon**
Fixes #140 

Now duplicate pastry with same name are not allow. Eg. Croissant vs crOiSSant

### CODE REVIEW

File: src/main/java/powerbake/address/model/AddressBook.java [hunk 1]
```diff
@@ -127,7 +128,15 @@ public void removePerson(Person key) {
...
-        return pastries.contains(pastry);
+        Stream<Pastry> duplicatePastry = pastries.asUnmodifiableObservableList()
+                .stream()
+                .filter(existing_pastry ->
+                        pastry.getName()
+                                .toString()
+                                .equalsIgnoreCase(existing_pastry
+                                        .getName()
+                                        .toString()));
+        return duplicatePastry.findAny().isPresent();
```
Comment (mihirniyogi) [inline src/main/java/powerbake/address/model/AddressBook.java:139]: good, neat use of functional programming
