### PR TITLE
Fix error message for pastry not exist 

### LINKED ISSUE #309: [PE-D][Tester B] Incorrect message when adding non-existent pastry in order
### Description:
When specifying a valid pastry name that does not exist, an inaccurate/unspecific exception message is shown as the pastry name is in the correct format, just that it does not exist.

### Steps to Reproduce:
`add order 1 -pn puffs -q 1`

### Expected Behavior:
Pastry does not exist in the bakery

### Observed Behavior:
`The pastry name provided is invalid`

### Screenshot(s):

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Zhannyhong/ped#13

### PR DESCRIPTION
**Pull request by mihirniyogi**
Fixes #309

### CODE REVIEW

File: src/main/java/powerbake/address/logic/Messages.java [hunk 1]
```diff
@@ -22,7 +22,7 @@ public class Messages {
     public static final String MESSAGE_INVALID_PASTRY_DISPLAYED_INDEX = "The pastry index provided is invalid. %1$s";
     public static final String MESSAGE_INVALID_ORDER_DISPLAYED_INDEX = "The order index provided is invalid. %1$s";
     public static final String MESSAGE_INVALID_INDEX = "The index provided is out of range.";
-    public static final String MESSAGE_INVALID_PASTRY_DISPLAYED = "The pastry name provided is invalid";
+    public static final String MESSAGE_INVALID_PASTRY_DISPLAYED = "The pastry does not exist.";
```
Comment (Emmanuel2001) [inline src/main/java/powerbake/address/logic/Messages.java:25]: This makes it more clear to the user. Good job!

**Review by Emmanuel2001 — COMMENTED** [review]
LGTM!

**Review by mogmyij — COMMENTED** [review]
LGTM!
